apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service-product-service  # 👈 Must match template labels
  template:
    metadata:
      labels:
        app: product-service-product-service  # 👈 Must match selector labels
    spec:
      containers:
        - name: product-service-product-service
          image: jaiswaramarjeet19876/product-service-product-service:latest
          env:
          - SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/productService
          - SPRING_DATASOURCE_USERNAME: root
          - SPRING_DATASOURCE_PASSWORD: techbankRootPsw
          ports:
            - containerPort: 8080