apiVersion: v1
kind: Service
metadata:
  name: product-service-be-fullstack
spec:
  selector:
    app: product-service-be-fullstack
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer