spring:
  h2:
    console:
      enabled: true # Enable H2 console
  datasource:
    url: jdbc:mysql://localhost:3306/productService
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: techbankRootPsw
    hikari:
      maximum-pool: 20
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 1800000
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  application:
    name: product-service

server:
  port: 8080
  
# Thread Pool properties
executor:
  corePoolSize: 5
  maxPoolSize: 10
  queueCapacity: 25
  threadNamePrefix: AsyncExecutor-


     