spring:
  datasource:
    url: jdbc:mysql://mysql:3306/productService
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: techbankRootPsw
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  batch:
    initialize-schema: never
  application:
    name: product-service

server:
  port: 8080
  
# Thread Pool properties
executor:
  corePoolSize: 5
  maxPoolSize: 10
  queueCapacity: 25
  threadNamePrefix: AsyncExecutor-


     